### ISSUE TITLE
Insert video button not working

### ISSUE THREAD

**Issue by Syxton** [Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor#17]
![screenshot](https://user-images.githubusercontent.com/989354/61309654-93fe8080-a7c0-11e9-9b62-1958f2b91ece.png)

Moodle 3.7
Tinymce Editor used
Chrome Version 75.0.3770.100 (Official Build) (64-bit)

Pressing the Insert button causes the following error:

panoptowrapper.html:108 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'rose-hulman.hosted.panopto.com' in a call to 'postMessage'.
    at HTMLButtonElement.<anonymous> (https://moodle.rose-hulman.edu/lib/editor/tinymce/plugins/panoptobutton/tinymce/panoptowrapper.html:108:21)
    at HTMLButtonElement.dispatch (https://moodle.rose-hulman.edu/lib/editor/tinymce/plugins/panoptobutton/tinymce/js/jquery-1.11.0.min.js:3:8066)
    at HTMLButtonElement.r.handle (https://moodle.rose-hulman.edu/lib/editor/tinymce/plugins/panoptobutton/tinymce/js/jquery-1.11.0.min.js:3:4767)
(anonymous) @ panoptowrapper.html:108
dispatch @ VM297 jquery-1.11.0.min.js:3
r.handle @ VM297 jquery-1.11.0.min.js:3
rose-hulman.js?version=20190711:1 [Violation] 'setInterval' handler took 101ms

**Comment by Syxton** [comment]
Pull request #18

**Comment by jmalmsten-panopto** [comment]
Thank you for catching this issue, it slipped past my tests before the last release. I will be including a fix for this issue in today's updated release.

Thank you for your patience,
Joe
